### ISSUE TITLE
Broken footnote in the source service chapter

### ISSUE THREAD

**Issue by dcermak** [openSUSE/obs-docu#173]
The following reference does not appear to work anymore:
https://github.com/openSUSE/obs-docu/blob/e8556bf78b6ab5c0f96db1ff6922232dfd63c76b/xml/obs_source_service.xml#L201

It renders as `???` in the column "runs locally" in the 5th row in the following table https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.source_service.html#sec.obs.sserv.mode

**Comment by tomschr** [comment]
Thanks for your bug report, much appreciated. :+1: 

Just to give you some background:
Actually, it's not the markup, but our (SUSE) stylesheets. In the official doc we don't use footnotes ATM, but we might use them in the future. As such, anything regarding footnotes is either disabled or not implemented. If you use the original DocBook stylesheets, this will work of course.

For example, if you reference a footnote with `<xref/>`, it won't work because it's not implemented. In case you use `<footnoteref/>` it works as that code uses the original, unmodified implementation from the DocBook stylesheets.
